---
- name: "Bring online all offline disks, initialize, and format"
  win_shell: |
    # Bring online all offline disks, initialize them, format as NTFS with custom cluster size, and assign drive letters
    Get-Disk | Where-Object { $_.OperationalStatus -eq 'Offline' } | ForEach-Object {
        $disk = $_

        # Bring the disk online
        Set-Disk -Number $disk.Number -IsOffline $False

        # Initialize the disk (use GPT or MBR depending on your requirement)
        Initialize-Disk -Number $disk.Number -PartitionStyle {{ partition_style }}

        # Create a new partition that uses all available space and assign a drive letter
        $partition = New-Partition -DiskNumber $disk.Number -UseMaximumSize -AssignDriveLetter

        # Format the partition as NTFS with a custom cluster size and assign a label
        Format-Volume -Partition $partition -FileSystem {{ file_system_type }} -AllocationUnitSize {{ allocation_unit_size }} -NewFileSystemLabel "{{ volume_label }}" -Confirm:$false

        # Retrieve the assigned drive letter
        $driveLetter = (Get-Partition -PartitionNumber $partition.PartitionNumber -DiskNumber $disk.Number).DriveLetter

        Write-Host "Disk number $($disk.Number) has been initialized, formatted, and assigned drive letter ${driveLetter}:"
    }
